# -*- coding: utf-8 -*-
"""Método da Secante.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cp1-TGWnwnkaQVprLrcPKDAgk5vizQR4
"""

#Mateus_Louzada-136197
#Metodo_da_Secante
#Resumo: O método da secante é uma técnica numérica utilizada para encontrar as raízes de uma função real.
#É uma variação do método de Newton que não requer a computação da derivada da função.
#Em vez disso, ele estima a derivada usando uma secante que passa pelos pontos iniciais fornecidos.

def f(x):
    # Defina a função a ser usada, por exemplo: f(x) = x^2 - 4
    return x**2 - 4

def secant_method(f, x0, x1, tol=1e-6, max_iter=1000):
    iter = 0
    while iter < max_iter:
        x2 = x1 - ((f(x1) * (x0 - x1)) / (f(x0) - f(x1)))
        ea = abs((x2 - x1) / x2) * 100  # Erro relativo aproximado (%)
        if ea < tol:
            return x2  # Aproximação da raiz
        x0 = x1
        x1 = x2
        iter += 1
    print("Não foi encontrada uma raiz dentro dos critérios definidos.")
    return None

# Escolha dois pontos iniciais próximos, x0 e x1
x0 = 1.5
x1 = 2

# Chame o método da secante
root = secant_method(f, x0, x1)

if root is not None:
    print("A raiz aproximada é:", root)